### ISSUE TITLE
[matrix vis] minor bug number 2

### ISSUE THREAD

**Issue by chongwei729** [Visual-Intelligence-UMN/GNN-101#148]
<img width="601" alt="Screenshot 2024-07-23 at 00 18 34" src="https://github.com/user-attachments/assets/956432a1-ee62-44ec-849f-ea7e1c4f9269">

I believe this has been mentioned several weeks before... sorry to bring this up again...

The adjacency matrix doesn't seem to interact properly

**Comment by HarryLuUMN** [comment]
Could you share how can we reproduce this bug?
