### ISSUE TITLE
[graph] sometimes, the node 1 and node 0 in the second layer interactions will fail

### ISSUE THREAD

**Issue by HarryLuUMN** [Visual-Intelligence-UMN/GNN-101#161]
trigger event: still in investigation

if it's a rare bug, skip it; if it's a common bug, fix it

https://github.com/user-attachments/assets/b2cf9ae0-46cb-4881-bf16-d3cb8fbe7faa

**Comment by chongwei729** [comment]
Somehow it is automatically fixed...... No idea what happened. Anyway the bug is gone
