### ISSUE TITLE
[p0] [graph] displayer is wrong btw last gcnconv and fc layers(node classifier)

### ISSUE THREAD

**Issue by HarryLuUMN** [Visual-Intelligence-UMN/GNN-101#187]
![image](https://github.com/user-attachments/assets/e8ba1a8d-1685-4bc6-b8b2-01b48b99bd69)

**Comment by chongwei729** [comment]
WHat do you mean by wrong? is it anything wrong with the shown data?

**Comment by HarryLuUMN** [comment]
For node classifier, you need have four numbers on the denominator, please check matrix visualizer for the correct one
